### ISSUE TITLE
Не верный расчет общего баланса при пополнении.

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/java_diplom#1]
# Описание
При пополнении суммы больше нуля, если на счету уже есть некая сумма, то не верно рассчитывается общий баланс. Сумма на счету не берется во внимание.

# Локация дефекта
https://github.com/Alexnoh87/java_diplom/blob/218880800612e1e4f1ae11fe56cf40ec10012e7e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L66-L70

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/java_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Создать тест со значениями конструктора:

```
initialBalance = 1_000,
creditLimit = 5_000,
rate =  15
```
3. Вызвать в тесте метод `add` cо значением 1_000
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс счёта равен 2_000
*Фактический результат:* Баланс счёта равен 1_000

# Скриншот проверяющего теста
![image](https://github.com/Alexnoh87/java_diplom/assets/128059717/ede2bbc9-06fb-41b7-b453-b1531ea8ef97)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
