### ISSUE TITLE
Не верная логика работы перевода на сберегательный счёт, если сумма по итогу будет выше максимально допустимой.

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/java_diplom#18]
# Описание
При переводе с кредитного счёта на сберегательный счёт суммы, превышающей максимальный баланс этого счёта, происходит списание средств, хотя, по логике работы и по условию, операция не должна быть выполнена и суммы на счетах должны остаться на прежнем уровне.

# Локация дефекта
https://github.com/Alexnoh87/java_diplom/blob/a8d88703e52075909d7d5dc8aa0d7de6f30f0486/src/main/java/ru/netology/javaqadiplom/Bank.java#L17

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/java_diplom/blob/main/src/main/java/ru/netology/javaqadiplom/Bank.java) в IDEA
2. Создать тест со значениями конструкторов:

```
CreditAccount
initialBalance = 5_000,
creditLimit = 5_000,
rate =  15

SavingAccount
initialBalance = 6_000,
minBalance = 1_000,
maxBalance = 10_000,
rate =  10
```
3. Вызвать в тесте метод `transfer`, перевод с `credit` на `saving` cо значением 5_000
4. Запустить тест с выводом результатов балансов обоих счетов
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс счёта `credit` равен 5_000, Баланс счёта `saving` равен 6_000
*Фактический результат:* Баланс счёта `credit` равен 0

# Скриншот проверяющего теста
![image](https://github.com/Alexnoh87/java_diplom/assets/128059717/3f850029-a808-40c1-b716-fc9262c71257)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
