### ISSUE TITLE
Не выполняются техусловия на отрицательный кредитный лимит

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/java_diplom#3]
# Описание
При отрицательном кредитном лимите (creditLimit) не выкидывается исключение вида IllegalArgumentException, отсутствует данный метод.

# Локация дефекта
https://github.com/Alexnoh87/java_diplom/blob/218880800612e1e4f1ae11fe56cf40ec10012e7e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/java_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Создать тест на исключения со значениями конструктора:

```
initialBalance = 2_000,
creditLimit = -5_000,
rate =  15
```
3. Запустить тест
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Выкидывается исключение вида IllegalArgumentException, программа удачно завершается.
*Фактический результат:* Программа завершается с ошибкой.

# Скриншот проверяющего теста
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/62416910-fc84-492f-876e-e60f93089e93)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
