### ISSUE TITLE
Не верный расчет итогового баланса при покупке на собственные средства. Баланс на покупку достаточный.

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/java_diplom#4]
# Описание
При покупке на сумму больше нуля и при достаточном балансе (initialBalance) на счёте (покупка не превышает сумму баланса), не верно рассчитывается остаток баланса.

# Локация дефекта
https://github.com/Alexnoh87/java_diplom/blob/218880800612e1e4f1ae11fe56cf40ec10012e7e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L47

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/java_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Создать тест со значениями конструктора:

```
initialBalance = 5_000,
creditLimit = 5_000,
rate =  15
```
3. Вызвать в тесте метод `pay` cо значением 3_000
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс счёта равен 2_000
*Фактический результат:* Баланс счёта равен -3_000

# Скриншот проверяющего теста
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/be6d9149-09b0-4eeb-94bc-8afb80c5d18f)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
